import IconTooltip from '../../shared/components/TipoSolicitud';
import { FaEye } from "react-icons/fa";

export const columnsAsignacionesLider = [
    {
        key: 'solicitud',
        label: 'Solicitud',
        renderComponent: (rowData: any) => <IconTooltip solicitud={rowData.solicitud} />,
    },
    {
        key: 'registro_tablaAsignacionARiesgo',
        label: 'Registro',
        hasModal: true
    },
    {
        key: 'radicado',
        label: 'Radicado',
    },
    {
        key: 'dias_habiles',
        label: 'Días hábiles',
    },
    {
        key: 'tipo_estudio',
        label: 'Tipo de Estudio',
    },
    {
        key: 'nombre',
        label: 'Nombre completo',
    },
    {
        key: 'nuip',
        label: 'Numero de Identificación',
    },
    {
        key: 'celular',
        label: 'Teléfono o Celular',
    },
    {
        key: 'correo',
        label: 'Correo electrónico',
    },
    {
        key: 'departamento',
        label: 'Departamento',
    },
    {
        key: 'municipio',
        label: 'Municipio',
    },
    
]

export const dataAsignacionesLider = [
    {
        solicitud: 3,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '9',
        tipo_estudio: 'Estudio por primera vez',
        nombre: 'Lukas rendon',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    },
    {
        solicitud: 1,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '3',
        tipo_estudio: 'Reevaluación por temporalidad',
        nombre: 'Camilo Sarmiento',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    }, {
        solicitud: 4,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '25',
        tipo_estudio: 'Reevaluación por hechos sobrevinientes',
        nombre: 'Lukas rendon',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    }, {
        solicitud: 2,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '17',
        tipo_estudio: 'Devolución por CERREM',
        nombre: 'Camilo Sarmiento',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    },
    {
        solicitud: 4,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '5',
        tipo_estudio: 'Evaluación de riesgo otra solicitud',
        nombre: 'Lukas rendon',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    },
    {
        solicitud: 5,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '3',
        tipo_estudio: 'Evaluación de riesgo otra solicitud',
        nombre: 'Camilo Sarmiento',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    }, {
        solicitud: 3,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '18',
        tipo_estudio: 'Evaluación de riesgo otra solicitud',
        nombre: 'Lukas rendon',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    }, {
        solicitud: 2,
        registro_tablaAsignacionARiesgo: '00001',
        radicado: 'EXT 2024 000078',
        dias_habiles: '35',
        tipo_estudio: 'Evaluación de riesgo otra solicitud',
        nombre: 'Camilo Sarmiento',
        nuip: '1.021.963.741',
        celular: '350 220 4049',
        correo: 'lucas.rendon@unp.gov.co',
        departamento: 'Bogotá D.C.',
        municipio: 'Bogotá D.C.',
    },
]